version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"              
    schedule:
      interval: "weekly"       
    commit-message:
      prefix: "chore(deps)"     
    open-pull-requests-limit: 5