# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    # Install dependencies
    - name: Install Dependencies
      run: go mod tidy

    # Linting
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.2
    - name: Run golangci-lint
      run: golangci-lint run ./...

    # Security scan
    - name: Install gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest
    - name: Run gosec security scan
      run: gosec ./...

    # Run tests with coverage
    - name: Test with Coverage
      run: go test -coverprofile=coverage.out ./...

    # Upload coverage to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
        flags: unittests
        name: codecov-go